name: Action Workflow

on:
    push:
        branches:
            - master
            - 'feature/*'
            - 'feature/**'
        branches-ignore:
            - null
        tags:
            - v1.*
        paths:
            - '**.js'
            - "!filename.js"
        paths-ignore:
            - 'docs/**'