name: Checkout Workflow

on: pull_request

jobs:
    run-github-checkout-action:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2.3.2
            - name: After Checkout
              run: |
                pwd
                ls -a
                echo $GITHUB_SHA
                echo $GITHUB_REPOSITORY
                echo $GITHUB_WORKSPACE
                echo "${{ github.token }}"
                # git clone git@github:$GITHUB_REPOSITORY
                # git checkout $GITHUB_SHA
