name: Checkout Workflow

on: push

jobs:
    run-github-checkout-action:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2.3.2
            - name: After Checkout
              run: |
                pwd
                ls -a