name: Container

on: pull_request

jobs:
    node_docker:
        runs-on: ubuntu-latest
        services:
            app:
                image: kishorenewton/node-api:latest 
                ports:
                    - 3000:3000
            mongo:
                image: mongo
                ports:
                    - "27017:27017"
        steps:
            - name: Post an user
              run: "curl -X POST http://localhost:3000/api/user -H 'Content-Type: application/json' -d '{\"username\": \"hello\", \"address\": \"dwded\"}'"
            - name: Get Users
              run: curl http://localhost:3000/api/user