name: Shell Commands

on: push

jobs: 
    run-shell-command:
        runs-on: ubuntu-latest
        steps: 
            - name: echo a string
              run: ehco "Hello from github action"
            - name: multiline script
              run: |
                node -v
                npm -v

    run-another-one:
        runs-on: ubuntu-16.04
        steps:
            - name: echo a string
              run: echo "Hello from old ubuntu os"
